
-- Create the products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric,
  link text,
  image text,
  source text,
  search_query text, 
  scraped_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, but good practice)
alter table public.products enable row level security;

-- Create policy to allow all actions for now (or restrict as needed)
create policy "Enable all access for all users" on public.products
as permissive for all
to public
using (true)
with check (true);
